services:
  spark-master:
    build: .
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark/apps
      - ./jars:/opt/spark/jars-extra
    networks:
      - lms_net

  spark-worker:
    build: .
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_NO_DAEMONIZE: "true"
    depends_on:
      - spark-master
    volumes:
      - ./apps:/opt/spark/apps
      - ./jars:/opt/spark/jars-extra
    ports:
      - "8081:8081"
    networks:
      - lms_net

networks:
  lms_net:
    external: true